//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fxpa.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fxpa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ADD {
            get {
                object obj = ResourceManager.GetObject("ADD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ADD2 {
            get {
                object obj = ResourceManager.GetObject("ADD2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap address_book {
            get {
                object obj = ResourceManager.GetObject("address_book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap address_book2 {
            get {
                object obj = ResourceManager.GetObject("address_book2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alarmclock_preferences {
            get {
                object obj = ResourceManager.GetObject("alarmclock_preferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_red {
            get {
                object obj = ResourceManager.GetObject("arrow_down_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_red_24 {
            get {
                object obj = ResourceManager.GetObject("arrow_down_red_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_in {
            get {
                object obj = ResourceManager.GetObject("arrow_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_green {
            get {
                object obj = ResourceManager.GetObject("arrow_up_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_green_24 {
            get {
                object obj = ResourceManager.GetObject("arrow_up_green_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid block size..
        /// </summary>
        internal static string BFALGO_INVALID_BLOCKSIZE {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_BLOCKSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only ECB and CBC modes are supported..
        /// </summary>
        internal static string BFALGO_INVALID_CIPHERMODE {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_CIPHERMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IV length..
        /// </summary>
        internal static string BFALGO_INVALID_IV_LENGTH {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_IV_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key size..
        /// </summary>
        internal static string BFALGO_INVALID_KEYSIZE {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_KEYSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PKCS7 padding data {0} at {1}..
        /// </summary>
        internal static string BFALGO_INVALID_PADDATA_PKCS7_2 {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_PADDATA_PKCS7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ANSIX923 padding value {0}..
        /// </summary>
        internal static string BFALGO_INVALID_PADVAL_ANSIX923_1 {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_PADVAL_ANSIX923_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PKCS7 padding value {0}..
        /// </summary>
        internal static string BFALGO_INVALID_PADVAL_PKCS7_1 {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_PADVAL_PKCS7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonzero ANSIX923 padding data {0} at {1}..
        /// </summary>
        internal static string BFALGO_NONZERO_PADDATA_ANSIX923_2 {
            get {
                return ResourceManager.GetString("BFALGO_NONZERO_PADDATA_ANSIX923_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected last block count {0}..
        /// </summary>
        internal static string BFALGO_UNEXPECTED_LAST_BLOCK_COUNT_1 {
            get {
                return ResourceManager.GetString("BFALGO_UNEXPECTED_LAST_BLOCK_COUNT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown padding {0} for final decryption..
        /// </summary>
        internal static string BFALGO_UNKNOWN_PADDING_DECRYPT_1 {
            get {
                return ResourceManager.GetString("BFALGO_UNKNOWN_PADDING_DECRYPT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown padding {0} for final encryption..
        /// </summary>
        internal static string BFALGO_UNKNOWN_PADDING_ENCRYPT_1 {
            get {
                return ResourceManager.GetString("BFALGO_UNKNOWN_PADDING_ENCRYPT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported padding mode {0}..
        /// </summary>
        internal static string BFALGO_UNSUPPORTED_PADDINGMODE_1 {
            get {
                return ResourceManager.GetString("BFALGO_UNSUPPORTED_PADDINGMODE_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Blip {
            get {
                return ResourceManager.GetStream("Blip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap BOOKS {
            get {
                object obj = ResourceManager.GetObject("BOOKS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap breakpoint {
            get {
                object obj = ResourceManager.GetObject("breakpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap breakpoint_selection {
            get {
                object obj = ResourceManager.GetObject("breakpoint_selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap breakpoints {
            get {
                object obj = ResourceManager.GetObject("breakpoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_cancel_12 {
            get {
                object obj = ResourceManager.GetObject("button_cancel_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_cancel_12_b {
            get {
                object obj = ResourceManager.GetObject("button_cancel_12_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CABINET {
            get {
                object obj = ResourceManager.GetObject("CABINET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CHART {
            get {
                object obj = ResourceManager.GetObject("CHART", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CHECKS {
            get {
                object obj = ResourceManager.GetObject("CHECKS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream chimes {
            get {
                return ResourceManager.GetStream("chimes", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap coins {
            get {
                object obj = ResourceManager.GetObject("coins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap coins2 {
            get {
                object obj = ResourceManager.GetObject("coins2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap coins3 {
            get {
                object obj = ResourceManager.GetObject("coins3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CONTRACT {
            get {
                object obj = ResourceManager.GetObject("CONTRACT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cube_green {
            get {
                object obj = ResourceManager.GetObject("cube_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cube_yellow {
            get {
                object obj = ResourceManager.GetObject("cube_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CUBES {
            get {
                object obj = ResourceManager.GetObject("CUBES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap currency_dollar {
            get {
                object obj = ResourceManager.GetObject("currency_dollar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap currency_dollar_grayscale {
            get {
                object obj = ResourceManager.GetObject("currency_dollar_grayscale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap currency_dollar1 {
            get {
                object obj = ResourceManager.GetObject("currency_dollar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dataupdate {
            get {
                object obj = ResourceManager.GetObject("dataupdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DELETE {
            get {
                object obj = ResourceManager.GetObject("DELETE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DELETE2 {
            get {
                object obj = ResourceManager.GetObject("DELETE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk_blue {
            get {
                object obj = ResourceManager.GetObject("disk_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DISKS {
            get {
                object obj = ResourceManager.GetObject("DISKS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dot {
            get {
                object obj = ResourceManager.GetObject("dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap element_next {
            get {
                object obj = ResourceManager.GetObject("element_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap element_selection {
            get {
                object obj = ResourceManager.GetObject("element_selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap environment_information {
            get {
                object obj = ResourceManager.GetObject("environment_information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EXCHANGE {
            get {
                object obj = ResourceManager.GetObject("EXCHANGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag {
            get {
                object obj = ResourceManager.GetObject("flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_blue {
            get {
                object obj = ResourceManager.GetObject("flag_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon fxpa_app {
            get {
                object obj = ResourceManager.GetObject("fxpa_app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HELP {
            get {
                object obj = ResourceManager.GetObject("HELP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read IV, no more data..
        /// </summary>
        internal static string JAVAIOP_CANNOT_READ_IV {
            get {
                return ResourceManager.GetString("JAVAIOP_CANNOT_READ_IV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid padding pattern..
        /// </summary>
        internal static string JAVAIOP_INVALID_PADDING_PATTERN {
            get {
                return ResourceManager.GetString("JAVAIOP_INVALID_PADDING_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid padding value..
        /// </summary>
        internal static string JAVAIOP_INVALID_PADVAL {
            get {
                return ResourceManager.GetString("JAVAIOP_INVALID_PADVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last block is truncated..
        /// </summary>
        internal static string JAVAIOP_LAST_BLOCK_TRUNCATED {
            get {
                return ResourceManager.GetString("JAVAIOP_LAST_BLOCK_TRUNCATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is truncated..
        /// </summary>
        internal static string JAVAIOP_TRUNCATED {
            get {
                return ResourceManager.GetString("JAVAIOP_TRUNCATED", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap kuf {
            get {
                object obj = ResourceManager.GetObject("kuf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap leftspine {
            get {
                object obj = ResourceManager.GetObject("leftspine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_edit {
            get {
                object obj = ResourceManager.GetObject("lock_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap magic_wand {
            get {
                object obj = ResourceManager.GetObject("magic_wand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap magifier_zoom_out {
            get {
                object obj = ResourceManager.GetObject("magifier_zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap magnifier_zoom_in {
            get {
                object obj = ResourceManager.GetObject("magnifier_zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_right {
            get {
                object obj = ResourceManager.GetObject("navigate_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap photo_scenery {
            get {
                object obj = ResourceManager.GetObject("photo_scenery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIN_GREY {
            get {
                object obj = ResourceManager.GetObject("PIN_GREY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress {
            get {
                object obj = ResourceManager.GetObject("progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_bar {
            get {
                object obj = ResourceManager.GetObject("progress_bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap selection_replace {
            get {
                object obj = ResourceManager.GetObject("selection_replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sound {
            get {
                object obj = ResourceManager.GetObject("sound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sound_none {
            get {
                object obj = ResourceManager.GetObject("sound_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sound1 {
            get {
                object obj = ResourceManager.GetObject("sound1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_tree {
            get {
                object obj = ResourceManager.GetObject("text_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TV {
            get {
                object obj = ResourceManager.GetObject("TV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WARNING {
            get {
                object obj = ResourceManager.GetObject("WARNING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
